XusinboyBekchanov/MyFbFramework

- IniFile.bas
- IniFile.bi
Add KeyRemove Function in IniFile
> Add KeyRemove Function in IniFile File

- examples/Canvas Example/ButterflyDraw.bas
- mff/Canvas.bas
- mff/Canvas.bi
Change all intger type  to double type as the same Cairo bi file
> Added: Scale function on windows.

- mff/UString.bas
- mff/UString.bi
> Add: Add function SaveToFile and LoadFromFile for UString

- mff/UString.bas
- mff/UString.bi
LoadFromFile function support Ansi, UTF8, Web UTF8 formatting now. Move outof namespace UString for wstring could be used also.
> Add: LoadFromFile, SaveToFile function.

- mff/UString.bas
- mff/UString.bi
Please testing with the updated function which I think it is better. It is work fine with chinese.
> Updated Function LoadFromFile to support UTF8

- mff/UString.bas
- mff/UString.bi
Change optional “AnsiFile As Boolean = False”  to "AnsiFile As Boolean = True" for open Ansi file more often than open UTF8 file.
> Updated Function LoadfromFile

- mff/Dictionary.bas
- mff/Dictionary.bi
- mff/WStringList.bas
- mff/WStringList.bi
Forgot pull this code last night? Do it again.
> Fixed: Improve the speed of Function IndexOf

- mff/UString.bas
- mff/UString.bi
It is better merger the function WLetEx and WLet into one function.
> Fixed: improve WLetEx

- mff/Grid.bas
- mff/GridData.bas
- mff/ListView.bas
- mff/TreeListView.bas
- mff/TreeView.bas
It is seem that change a lot code but add the code "If Index >= 0 AndAlso Index < FNodes.Count" only annd do a formatting
> Fixed: the Index of Items for all Control

- examples/mff/Manifest.xml
- examples/mff/ReduceCode.frm
- examples/mff/ReduceCode.rc
This should give more consideration to the relationship between each other, and it is recommended to establish several types of templates
> Added: ReduceCode.frm

- mff/Grid.bas
- mff/Grid.bi
GridCell was added only if the user specifies Editable, ForeColor or BackColor specifically for the cell. The default value is the backcolor of grid
> Added: add sub SaveToFIle and LoadFromFIle to control Grid

- mff/Bitmap.bas
- mff/Picture.bas
The  code could be Stretch the Image also.  ".Graphic.Bitmap.LoadFromResourceName("b_jiang", , This.Width, This.Height)"
> Fixed: can not load Bitmap in function LoadFromFile

- mff/Panel.bas
- mff/Panel.bi
- mff/Picture.bas
- mff/Picture.bi
This is not the  the best way to update the control with the right background.
> Fixed: Redraw while move the control inside Container

- mff/UString.bas
- mff/UString.bi
SubString can also be Copies a maximum of length characters of expression into text, starting at start.
> Added: add function SubString to UString

- mff/Label.bas
- mff/Label.bi
> Added: add AutoSize property for control Label

- examples/Canvas/CanvasDraw.bas
- mff/Canvas.bas
- mff/Canvas.bi
- mff/Control.bas
- mff/Form.bas
- mff/Graphic.bi
- mff/Panel.bas
- mff/Picture.bas
Drawing with both GDI and GDI+ simultaneously can be challenging. There is a need to improve and add more functions in the future.
> Fixed: Remove the sub CreateDoubleBuffer and TransferDoubleBuffer in Canvas

- inc/raylib.bi
- inc/raymath.bi
use namespace for easy access to types/constants and avoid multi definition.
> Added: Namespace to RayLib.bi

- examples/Media/fbsound/FBSound.frm
- inc/fbs3d.bi
- inc/fbsound-1.2/csid.bi
- inc/fbsound-1.2/dumb.bi
- inc/fbsound-1.2/fbs3d.bi
- inc/fbsound-1.2/fbscpu.bas
- inc/fbsound-1.2/fbscpu.bi
- inc/fbsound-1.2/fbsdsp.bas
- inc/fbsound-1.2/fbsdsp.bi
- inc/fbsound-1.2/fbsound.bas
- inc/fbsound-1.2/fbsound.bi
- inc/fbsound-1.2/fbstypes.bi
- inc/fbsound-1.2/mad.bi
- inc/fbsound-1.2/plug-alsa.bas
- inc/fbsound-1.2/plug-alsa.bi
- inc/fbsound-1.2/plug-arts.bas
- inc/fbsound-1.2/plug-arts.bi
- inc/fbsound-1.2/plug-ds.bas
- inc/fbsound-1.2/plug-ds.bi
- inc/fbsound-1.2/plug-dsp.bas
- inc/fbsound-1.2/plug-dsp.bi
- inc/fbsound-1.2/plug-mm.bas
- inc/fbsound-1.2/plug-mm.bi
- inc/fbsound-1.2/plug.bi
- inc/fbsound-1.2/vorbis.bi
- inc/fbsound_dynamic.bi
- inc/fbsound_oop.bi
Someone could be test the code in your computer.
> Added:   add FBSound examples

- examples/Canvas/cairo_fbgfx.frm
Minor change on behaviour of  cairo_image_surface_create_for_data
> 	modified:   examples/Canvas/cairo_fbgfx.frm

- mff/Application.bas
- mff/Application.bi
- mff/Control.bas
The path of DLL and Exe file is different.
> Added: Implemented PrevInstance function and Path in Application.Bas.

- inc/DynamicArrayList.bi
- inc/DynamicArrayList_Test.bas
- inc/Thread.bi
- inc/Thread_Test.bas
the code posted on the freeBasic forum(www.freebasic.net/forum/
> Added：Add files Thread.bi, DynamicArrayList.bi

- examples/mff/String build and Split function test.bas
- mff/NoInterface.bi
- mff/UString.bas
- mff/UString.bi
The speed has improved tenfold. So should we import the DynamicArrayList.bi for WStringList also？
> Fixed: improve split function speed and skip empty element.

- mff/Application.bas
- mff/Application.bi
Base on the source code of NotePad2
> Fixed: Updated function CheckUTF8NoBOM

- inc/pipe.bi
Ready for applications like Curl and Chess engine.
> Add: pipe.bi for improve command line

- .github/workflows/main.yml
- mff/Application.bas
- mff/IniFile.bas
- mff/IniFile.bi
Fix the bug and UTF-8 without BOM support
> Added: UTF-8 without BOM support for Ini File

- mff/RichTextBox.bas
This is not the best code to fix this issue
> Fixed: RichTextBox highlight missing after DPI change.

- mff/TextBox.bas
1. The ScrollBar property style changes according to the style of WordWraps
2. WordWraps changes keep the Caret position and Selection status
> Update Property TextBox.WordWraps(Value As Boolean)
